
package com.brolly.diary.service.impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrudServiceImplService", targetNamespace = "http://impl.service.diary.brolly.com/", wsdlLocation = "http://localhost:8888/web-diary/ws/entries?wsdl")
public class CrudServiceImplService
    extends Service
{

    private final static URL CRUDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRUDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CRUDSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.diary.brolly.com/", "CrudServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/web-diary/ws/entries?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRUDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CRUDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CrudServiceImplService() {
        super(__getWsdlLocation(), CRUDSERVICEIMPLSERVICE_QNAME);
    }

    public CrudServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRUDSERVICEIMPLSERVICE_QNAME, features);
    }

    public CrudServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CRUDSERVICEIMPLSERVICE_QNAME);
    }

    public CrudServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRUDSERVICEIMPLSERVICE_QNAME, features);
    }

    public CrudServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrudServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrudService
     */
    @WebEndpoint(name = "CrudServiceImplPort")
    public CrudService getCrudServiceImplPort() {
        return super.getPort(new QName("http://impl.service.diary.brolly.com/", "CrudServiceImplPort"), CrudService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrudService
     */
    @WebEndpoint(name = "CrudServiceImplPort")
    public CrudService getCrudServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.diary.brolly.com/", "CrudServiceImplPort"), CrudService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRUDSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CRUDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CRUDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }


}
