
package com.brolly.diary.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.brolly.diary.service.DiaryEntry;
import com.brolly.diary.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrudService", targetNamespace = "http://service.diary.brolly.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrudService {


    /**
     * 
     * @return
     *     returns java.util.List<com.brolly.diary.service.DiaryEntry>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDiaryEntries", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.GetAllDiaryEntries")
    @ResponseWrapper(localName = "getAllDiaryEntriesResponse", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.GetAllDiaryEntriesResponse")
    @Action(input = "http://service.diary.brolly.com/CrudService/getAllDiaryEntriesRequest", output = "http://service.diary.brolly.com/CrudService/getAllDiaryEntriesResponse")
    public List<DiaryEntry> getAllDiaryEntries();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.brolly.diary.service.DiaryEntry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOne", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.FindOne")
    @ResponseWrapper(localName = "findOneResponse", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.FindOneResponse")
    @Action(input = "http://service.diary.brolly.com/CrudService/findOneRequest", output = "http://service.diary.brolly.com/CrudService/findOneResponse")
    public DiaryEntry findOne(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.SayHelloResponse")
    @Action(input = "http://service.diary.brolly.com/CrudService/sayHelloRequest", output = "http://service.diary.brolly.com/CrudService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveDiaryEntry", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.SaveDiaryEntry")
    @ResponseWrapper(localName = "saveDiaryEntryResponse", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.SaveDiaryEntryResponse")
    @Action(input = "http://service.diary.brolly.com/CrudService/saveDiaryEntryRequest", output = "http://service.diary.brolly.com/CrudService/saveDiaryEntryResponse")
    public Integer saveDiaryEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        DiaryEntry arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateDiaryEntry", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.UpdateDiaryEntry")
    @ResponseWrapper(localName = "updateDiaryEntryResponse", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.UpdateDiaryEntryResponse")
    @Action(input = "http://service.diary.brolly.com/CrudService/updateDiaryEntryRequest", output = "http://service.diary.brolly.com/CrudService/updateDiaryEntryResponse")
    public void updateDiaryEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDiaryEntry", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.DeleteDiaryEntry")
    @ResponseWrapper(localName = "deleteDiaryEntryResponse", targetNamespace = "http://service.diary.brolly.com/", className = "com.brolly.diary.service.DeleteDiaryEntryResponse")
    @Action(input = "http://service.diary.brolly.com/CrudService/deleteDiaryEntryRequest", output = "http://service.diary.brolly.com/CrudService/deleteDiaryEntryResponse")
    public void deleteDiaryEntry(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
